### PR TITLE
Compatibility fixes for 'html-webpack-plugin' v4.0.0

### PR DESCRIPTION
**Pull request by ramondeklein**
Allow this plug-in to be used with html-webpack-plugin v4.0.0 alpha. See also #5.

### CODE REVIEW

**Comment by ramondeklein** [comment]
This fix adds support for 'html-webpack-plugin' v4, while still being compatible with v3.

**Comment by scink** [comment]
hi, @ramondeklein, thanx for trying to solve this problem (i have the same).
don't know if you notice but there is a problem with build of your pr.
i'll be really grateful if you can fix it, so @romanlex can merge it and release

**Comment by ramondeklein** [comment]
I think this project has been abondomned, because I didn't get any feedback from the author.

**Comment by scink** [comment]
@ramondeklein too sad to hear it. don't you know any analogues of this plugin?
for now i decided to use your fork for my project. hope, it will live long)

**Comment by romanlex** [comment]
@ramondeklein @scink hi all, sorry what I missing and don't looking this PR
In the coming days I merge this

**Comment by romanlex** [comment]
Will be released with v1.2.0

**Pull request merged**
